language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "11"
before_script:
    - cp config/database.yml.travis config/database.yml
before_install:
  - psql -c 'create database test_db;' -U postgres
  - cd backend
install:
  - pip3 install -r requirements.txt
script:
  - python3 manage.py test catalog/tests/unit_tests
  - python3 manage.py test catalog/tests/integration_tests
  - python3 manage.py test catalog/tests/e2e_test